/**
 * File templates the migrator can drop into a target repo.
 *
 * Every template is a pure function — no I/O, no clock — so the plan is
 * deterministic: running `plan` twice against the same input produces the
 * same output. That property is what lets `apply` consume a plan generated
 * minutes (or days) earlier without surprise.
 */

/** The Portfolio Standard's default top-level route list, used by R13. */
export function routesConfigJson(productSlug: string): string {
  // Two-space indent matches the rest of the @caistech/* package family
  // and is what `npx prettier` would produce on a JSON file.
  return JSON.stringify(
    {
      baseUrl:
        process.env.PORTFOLIO_GATE_PREVIEW_URL ??
        `https://${productSlug}.vercel.app`,
      routes: [
        { path: '/' },
        { path: '/pricing' },
        { path: '/about' },
        { path: '/contact' },
        { path: '/login' },
        { path: '/signup' },
        { path: '/forgot-password' },
        { path: '/privacy' },
        { path: '/terms' },
        { path: '/api/health', expectedStatus: 200 },
      ],
    },
    null,
    2
  ) + '\n';
}

/** Default auth config — every product has the same path layout. */
export function authConfigJson(): string {
  return (
    JSON.stringify(
      {
        baseUrl: '__OVERRIDE_FROM_CI__',
        loginPath: '/login',
        signupPath: '/signup',
        forgotPasswordPath: '/forgot-password',
        magicLinkPath: '/login',
        loginActionPath: '/api/auth/login',
        signupActionPath: '/api/auth/signup',
        forgotPasswordActionPath: '/api/auth/forgot',
        magicLinkActionPath: '/api/auth/magic-link',
      },
      null,
      2
    ) + '\n'
  );
}

/**
 * The gate.yml workflow. Identical to the template shipped in
 * `@caistech/portfolio-gate` so consumers receive the same CI surface
 * whether they install the gate directly or migrate via this CLI.
 */
export function gateWorkflowYml(): string {
  return `# Portfolio Standard gate — generated by @caistech/portfolio-migrator
#
# Runs typecheck + lint + build, then route + auth smoke tests against the
# preview deploy URL. Fails the action (and blocks Vercel promotion) on any
# non-zero exit.
#
# Closes Portfolio Standard:
#   R1  — Auth four-leg pattern (auth smoke step)
#   R10 — No verbatim Postgres errors (errorResponse helper, enforced at code level)
#   R13 — Route smoke test on every deploy (route smoke step)

name: portfolio-gate

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  gate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      PORTFOLIO_GATE_PREVIEW_URL: \${{ vars.PORTFOLIO_GATE_PREVIEW_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
        env:
          GITHUB_PACKAGES_TOKEN: \${{ secrets.CAISTECH_PACKAGES_TOKEN }}

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

      - name: Verify preview URL is set
        run: |
          if [ -z "$PORTFOLIO_GATE_PREVIEW_URL" ]; then
            echo "::error::PORTFOLIO_GATE_PREVIEW_URL is not set. Wire it via repo vars or a preview-deploy step."
            exit 1
          fi
          echo "Preview URL: $PORTFOLIO_GATE_PREVIEW_URL"

      - name: Route smoke test (Portfolio Standard R13)
        run: |
          npx --no-install portfolio-gate-smoke-routes \\
            --config routes.config.json \\
            --base-url "$PORTFOLIO_GATE_PREVIEW_URL"

      - name: Auth smoke test (Portfolio Standard R1/R4)
        run: |
          npx --no-install portfolio-gate-smoke-auth \\
            --config auth.config.json \\
            --base-url "$PORTFOLIO_GATE_PREVIEW_URL"
`;
}

/**
 * Vendor-identity placeholder block appended (or created) in `.env.example`.
 * Used by the `vendor-identity-env-defaults` migration step.
 */
export function vendorIdentityEnvBlock(): string {
  return `
# Portfolio Standard R11 — vendor identity routed through env vars.
# Replace the placeholders with the consuming brand's identity, or leave
# them as-is for a vendor-neutral white-label deploy.
NEXT_PUBLIC_VENDOR_NAME="Your Brand Here"
NEXT_PUBLIC_VENDOR_EMAIL="hello@yourbrand.com"
NEXT_PUBLIC_VENDOR_PHONE=""
NEXT_PUBLIC_VENDOR_CALENDLY=""
NEXT_PUBLIC_VENDOR_INSTAGRAM=""
`;
}

/**
 * The R6 RESEND_FROM_EMAIL placeholder block. Used by
 * `add-resend-from-email-example`.
 */
export function resendFromEmailBlock(): string {
  return `
# Portfolio Standard R6 — verified Resend subdomain (never the bare
# corporateaisolutions.com — not verified, silently fails delivery).
RESEND_FROM_EMAIL=noreply@updates.corporateaisolutions.com
`;
}

/**
 * Markdown body shown to the user inside the plan summary describing the
 * R1 swap. Too complex to auto-generate — the consumer's existing login
 * page may have custom branding, redirect URLs, or analytics hooks that
 * need preserving — so the migrator emits a Note + suggested AuthForm
 * usage they can adapt.
 */
export function authFormSwapNoteBody(productSlug: string): string {
  return `Replace every raw login / signup / forgot-password / reset-password page
with \`<AuthForm/>\` from \`@caistech/corporate-components\` (shipped in 0.2.0).

\`<AuthForm/>\` bakes in all four R1 legs (forgot-password link, password
visibility toggle, magic-link, email verification) plus mobile-first
responsive defaults (R2), 44 px tap targets, and a built-in
explanatory header per mode (R3).

### Example: \`app/login/page.tsx\`

\`\`\`tsx
'use client';
import { AuthForm } from '@caistech/corporate-components';
import { createBrowserClient } from '@supabase/ssr';

export default function LoginPage() {
  const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
  return (
    <AuthForm
      mode="login"
      supabase={supabase}
      brandName="${productSlug}"
      redirectTo="/dashboard"
    />
  );
}
\`\`\`

### What to review before swapping

- **Redirect URL.** Confirm \`redirectTo\` matches your post-login surface.
- **Custom branding.** If the existing login page has a hero / logo / illustration,
  pass it via the \`<AuthForm/>\`'s \`brandName\` + slot props rather than wrapping
  raw HTML around the form.
- **Analytics.** If the existing form fires a custom event on submit, wire it via
  the \`onSuccess\` callback rather than re-implementing the form.
- **Server actions.** \`<AuthForm/>\` uses the Supabase browser client directly.
  If your existing flow goes through a server action, you can keep that handler
  and pass a thin \`onSubmit\` to the form — but the default direct-client path is
  what the auth smoke test exercises.

This swap is **note-only** — the migrator does not auto-generate the new
pages because of the customisation surface above. Apply the swap by hand
and verify with \`npx portfolio-gate-smoke-auth\` before landing.`;
}

/**
 * Markdown body for the R9 RLS USING(true) note. Same reasoning as the
 * AuthForm swap — the replacement policy depends on the table's tenancy
 * model, which the migrator can't infer safely.
 */
export function rlsUsingTrueNoteBody(): string {
  return `One or more migrations contain \`USING (true)\` against a data-bearing
table — this violates Portfolio Standard R9.

\`USING (true)\` allows every authenticated row to read every other row's
data, which is a Privacy Act exposure on REGULATED and REVENUE tier
products. The naive-tester sweep on 2026-05-19 found this exact pattern
on Connexions, Universal Interviews, Platform-Trust, and Longtail-AIVS.

### How to fix

For each violation, write a new migration that:

1. \`DROP POLICY IF EXISTS <name> ON <table>;\`
2. \`CREATE POLICY <name> ON <table> FOR <ops> TO <role>
   USING (auth.uid() = <owner_column>);\`

The owner column varies per table — \`owner_id\`, \`user_id\`, \`org_id\`,
\`tenant_id\` are all common. The migrator cannot infer the correct column
safely, so this step is **note-only**.

### Verify

After applying, run:

\`\`\`bash
npx portfolio-gate-audit-rls
\`\`\`

It must report \`PASS\` before the deploy promotes.`;
}
