/**
 * Browser title audit — Portfolio Standard check #7.
 *
 * Browser <title> must be the product name, not scaffold default
 * "Create Next App" or similar.
 *
 * See: criteria.json → #7.
 */
import { resolve } from 'node:path'
import {
  type AuditFinding,
  type AuditResult,
  loadConfigOptional,
  readFileOptional,
  walkFiles,
} from './shared.js'

export interface BrowserTitleConfig {
  badTitles?: string[]
}

export interface BrowserTitleOptions {
  rootDir?: string
  configPath?: string | null
}

const DEFAULT_BAD_TITLES = [
  'Create Next App',
  'Next.js',
  'Generated by create next app',
  'React App',
  'Vite App',
  'Welcome to Next.js',
]

export async function runBrowserTitleAudit(
  options: BrowserTitleOptions = {}
): Promise<AuditResult> {
  const start = Date.now()
  const rootDir = options.rootDir ?? process.cwd()
  const config =
    (await loadConfigOptional<BrowserTitleConfig>(
      options.configPath ??
        resolve(rootDir, 'browser-title.config.json')
    )) ?? {}

  const badTitles = config.badTitles ?? DEFAULT_BAD_TITLES
  const findings: AuditFinding[] = []

  // Find layout files (handle both Windows \ and Unix / paths)
  const files = await walkFiles(rootDir, { extensions: ['.tsx', '.jsx'] })
  const layoutFiles = files.filter(f => 
    f.includes('/layout.tsx') || f.includes('\\layout.tsx') ||
    f.includes('/layout.jsx') || f.includes('\\layout.jsx') ||
    f.endsWith('/_document.tsx') || f.endsWith('\\document.tsx') ||
    f.endsWith('/_document.jsx') || f.endsWith('\\document.jsx')
  )

  let foundTitle = false
  let titleValue = ''

  for (const file of layoutFiles) {
    const content = await readFileOptional(file)
    if (!content) continue

    // Look for export const metadata = { title: ... } or export const viewport
    // More lenient - just check for metadata with title
    const hasMetadata = content.includes('export const metadata') && content.includes('title:')
    if (hasMetadata) {
      foundTitle = true
      const titleMatch = content.match(/title:\s*['"]([^'"]+)['"]/)
      if (titleMatch) titleValue = titleMatch[1]
      
      // Check if it's a bad title
      const isBad = badTitles.some(bad => 
        titleValue.toLowerCase().includes(bad.toLowerCase())
      )
      
      if (isBad) {
        findings.push({
          severity: 'fail',
          message: `browser <title> is "${titleValue}" - must be product name, not scaffold default`,
          file: file.replace(rootDir, '').replace(/\\/g, '/'),
        })
        break
      }
    }
  }

  if (!foundTitle) {
    findings.push({
      severity: 'fail',
      message: 'no <title> found in layout - must set product name',
      file: 'src/app/layout.tsx',
    })
  }

  return {
    audit: 'browser-title',
    rule: '#7',
    passed: findings.length === 0,
    findings,
    durationMs: Date.now() - start,
  }
}
