// elevenlabs-convai/voice-init.ts
// Pure config-building for the scaffold wizard (scripts/voice-init.mjs). Kept in the
// package (not the script) so the mapping is unit-tested. The wizard does the I/O
// (prompts, file write, provisioning) and calls these.

import type { VoiceConfig, VoicePlacement, VoiceMode } from './types.js';

export const PLACEMENTS: VoicePlacement[] = ['floating', 'sidebar', 'header', 'inline', 'fullpage'];
export const MODES: VoiceMode[] = ['greeting', 'clarifier', 'discovery', 'interview'];

export interface VoiceInitAnswers {
  placement: VoicePlacement;
  mode: VoiceMode;
  textFallback: boolean;
  /** UI surfaces where the voice agent acts as the in-context clarifier (free-text list). */
  clarifierFields?: string[];
  allowedOrigins?: string[];
}

/** Build a VoiceConfig from wizard answers + the provisioned agent id. */
export function buildVoiceConfig(agentId: string, answers: VoiceInitAnswers): VoiceConfig {
  if (!PLACEMENTS.includes(answers.placement)) {
    throw new Error(`voice-init: invalid placement "${answers.placement}". One of: ${PLACEMENTS.join(', ')}`);
  }
  if (!MODES.includes(answers.mode)) {
    throw new Error(`voice-init: invalid mode "${answers.mode}". One of: ${MODES.join(', ')}`);
  }
  const config: VoiceConfig = {
    agentId,
    placement: answers.placement,
    mode: answers.mode,
    textFallback: answers.textFallback,
    personaRef: 'voice-config.json',
  };
  if (answers.allowedOrigins && answers.allowedOrigins.length > 0) {
    config.allowedOrigins = answers.allowedOrigins;
  }
  return config;
}

/** Render the voice.config.ts module text emitted into the target project. */
export function renderVoiceConfigModule(config: VoiceConfig, clarifierFields?: string[]): string {
  const header =
    '// voice.config.ts — generated by the @caistech/elevenlabs-convai voice-init wizard.\n' +
    '// Consumed by <VoiceWidget {...voiceConfig} /> and by provisioning.\n';
  const clarifier = clarifierFields && clarifierFields.length > 0
    ? `// Clarifier surfaces (where the agent helps with nuanced input):\n//   ${clarifierFields.join(', ')}\n`
    : '';
  return (
    `${header}${clarifier}` +
    `import type { VoiceConfig } from '@caistech/elevenlabs-convai';\n\n` +
    `export const voiceConfig: VoiceConfig = ${JSON.stringify(config, null, 2)};\n`
  );
}
