-- promise_attributes: ratified bars for f2k-projects + lessonslearned
-- Fable-5 drafted, operator-greenlit 2026-07-10. Idempotent (delete-then-insert).
-- Apply to the cockpit instance (promise_attributes table). VERIFY the linked ref first.
BEGIN;
DELETE FROM promise_attributes WHERE product_slug IN ('f2k-projects', 'lessonslearned');
INSERT INTO promise_attributes
  (product_slug, promise, distributor, attribute, quality_bar, verify, sort_order)
VALUES
  ('f2k-projects', 'Browse a land estate like a premium product, pick your lot, and walk away with a configured, priced proposal in the same session', 'Land-estate developers & project marketers', 'Premium lot browse', 'every lot on an interactive estate plan opens to its own detail card (size, frontage, orientation, price, live status) in one click - not a static masterplan PDF or an undifferentiated table of lot numbers', 'NAIVE', 0),
  ('f2k-projects', 'Browse a land estate like a premium product, pick your lot, and walk away with a configured, priced proposal in the same session', 'Land-estate developers & project marketers', '''I want THAT lot'' moment', 'a specific lot feels ownable - the detail view shows what living/building THERE looks like (aspect, dimensions on the plan, what fits on it) so a viewer names a favourite lot unprompted - not interchangeable rectangles with prices', 'NAIVE/JUDGE', 1),
  ('f2k-projects', 'Browse a land estate like a premium product, pick your lot, and walk away with a configured, priced proposal in the same session', 'Land-estate developers & project marketers', 'Hot-configured proposal', 'registering interest on a lot produces a branded proposal specific to THAT lot with real configured numbers (lot price + selected package/options) inside the session or within minutes - not a ''thanks, we''ll be in touch'' acknowledgement', 'NAIVE', 2),
  ('f2k-projects', 'Browse a land estate like a premium product, pick your lot, and walk away with a configured, priced proposal in the same session', 'Land-estate developers & project marketers', 'Live estate truth', 'lot availability (available/held/sold) is current and consistent everywhere it appears, and a just-registered interest visibly changes state - not stale statuses that make the estate feel abandoned', 'NAIVE', 3),
  ('f2k-projects', 'Browse a land estate like a premium product, pick your lot, and walk away with a configured, priced proposal in the same session', 'Land-estate developers & project marketers', 'Distributor pull (qualified leads)', 'the developer''s admin view shows leads arriving already qualified - lot chosen, configuration captured, proposal sent - under the ESTATE''s brand end-to-end - not raw name+email enquiries they must re-qualify by phone', 'NAIVE/JUDGE', 4),
  ('lessonslearned', 'Speak a hard-won lesson in seconds and have exactly the right past lesson resurface when you next need it', 'Consultancies, trade businesses & field-service teams that accumulate field knowledge', 'Frictionless voice capture', 'tap, speak naturally, done - a usable distilled lesson exists within ~15 seconds of finishing speaking, with zero typing or transcript cleanup required - not a recording the user must title, tag, and edit', 'NAIVE', 0),
  ('lessonslearned', 'Speak a hard-won lesson in seconds and have exactly the right past lesson resurface when you next need it', 'Consultancies, trade businesses & field-service teams that accumulate field knowledge', 'Distillation quality', 'the stored item is a crisp situation-plus-lesson the speaker recognises as ''yes, that''s what I meant'' - context preserved, rambling removed - not a raw transcript dump or an over-summarised platitude that lost the specifics', 'JUDGE', 1),
  ('lessonslearned', 'Speak a hard-won lesson in seconds and have exactly the right past lesson resurface when you next need it', 'Consultancies, trade businesses & field-service teams that accumulate field knowledge', 'Semantic recall', 'asking in COMPLETELY different words than the original capture (zero keyword overlap) surfaces the right prior lesson as the top result - not keyword search that only finds exact phrasings', 'NAIVE/JUDGE', 2),
  ('lessonslearned', 'Speak a hard-won lesson in seconds and have exactly the right past lesson resurface when you next need it', 'Consultancies, trade businesses & field-service teams that accumulate field knowledge', 'Unprompted resurfacing', 'while capturing or working on a NEW situation, a genuinely related prior lesson surfaces on its own (''you hit something like this in March...'') - not a library the user must remember to search', 'NAIVE', 3),
  ('lessonslearned', 'Speak a hard-won lesson in seconds and have exactly the right past lesson resurface when you next need it', 'Consultancies, trade businesses & field-service teams that accumulate field knowledge', 'Distributor pull (team brain)', 'a team lead sees the team''s collective lesson base compound across members - one member''s field lesson recallable by another, with attribution - not per-person silos or a usage counter', 'JUDGE', 4);
COMMIT;
